import math


class BirdClearSkyModel:
    def __init__(
        self,
        lat: float = 40.0,
        long: float = -105.0,
        tz: float = -7.0,
        pressure_m_b: float = 840.0,
        ozone_cm: float = 0.3,
        h2_o_cm: float = 1.5,
        aod_500_nm: float = 0.1,
        aod_380_nm: float = 0.15,
        ba: float = 0.85,
        albedo: float = 0.2,
        doy: float = 1.0,
        hr: float = 1.0,
    ):
        """
        Autogenerated method
        Args:
            lat: Auto-generated variable defined at A9.
            long: Auto-generated variable defined at A11.
            tz: Auto-generated variable defined at A13.
            pressure_m_b: Auto-generated variable defined at A15.
            ozone_cm: Auto-generated variable defined at A17.
            h2_o_cm: Auto-generated variable defined at A19.
            aod_500_nm: Auto-generated variable defined at A21.
            aod_380_nm: Auto-generated variable defined at A23.
            ba: Auto-generated variable defined at A27.
            albedo: Auto-generated variable defined at A29.
            doy: Auto-generated variable defined at B3.
            hr: Auto-generated variable defined at C3."""
        self.lat = lat
        self.long = long
        self.tz = tz
        self.pressure_m_b = pressure_m_b
        self.ozone_cm = ozone_cm
        self.h2_o_cm = h2_o_cm
        self.aod_500_nm = aod_500_nm
        self.aod_380_nm = aod_380_nm
        self.ba = ba
        self.albedo = albedo
        self.doy = doy
        self.hr = hr

    def taua(self):
        """
        Autogenerated method
        Excel formula defined in cell A25
        Original formula: =0.2758*$A$23+0.35*$A$21"""
        return 0.2758 * self.aod_380_nm + 0.35 * self.aod_500_nm

    def etr(self):
        """
        Autogenerated method
        Excel formula defined in cell D3
        Original formula: =1367*(1.00011+0.034221*COS(2*PI()*(B3-1)/365)+0.00128*SIN(2*PI()*(B3-1)/365)+0.000719*COS(2*(2*PI()*(B3-1)/365))+0.000077*SIN(2*(2*PI()*(B3-1)/365)))"""
        return 1367.0 * (
            1.00011
            + 0.034221 * math.cos(2.0 * math.pi * (self.doy - 1.0) / 365.0)
            + 0.00128 * math.sin(2.0 * math.pi * (self.doy - 1.0) / 365.0)
            + 0.000719 * math.cos(2.0 * (2.0 * math.pi * (self.doy - 1.0) / 365.0))
            + 7.7e-05 * math.sin(2.0 * (2.0 * math.pi * (self.doy - 1.0) / 365.0))
        )

    def dangle(self):
        """
        Autogenerated method
        Excel formula defined in cell E3
        Original formula: =6.283185*(B3-1)/365"""
        return 6.283185 * (self.doy - 1.0) / 365.0

    def dec(self):
        """
        Autogenerated method
        Excel formula defined in cell F3
        Original formula: =(0.006918-0.399912*COS(E3)+0.070257*SIN(E3)-0.006758*COS(2*E3)+0.000907*SIN(2*E3)-0.002697*COS(3*E3)+0.00148*SIN(3*E3))*(180/3.14159)"""
        return (
            0.006918
            - 0.399912 * math.cos(self.dangle())
            + 0.070257 * math.sin(self.dangle())
            - 0.006758 * math.cos(2.0 * self.dangle())
            + 0.000907 * math.sin(2.0 * self.dangle())
            - 0.002697 * math.cos(3.0 * self.dangle())
            + 0.00148 * math.sin(3.0 * self.dangle())
        ) * (180.0 / 3.14159)

    def eqt(self):
        """
        Autogenerated method
        Excel formula defined in cell G3
        Original formula: =(0.0000075+0.001868*COS(E3)-0.032077*SIN(E3)-0.014615*COS(2*E3)-0.040849*SIN(2*E3))*(229.18)"""
        return (
            7.5e-06
            + 0.001868 * math.cos(self.dangle())
            - 0.032077 * math.sin(self.dangle())
            - 0.014615 * math.cos(2.0 * self.dangle())
            - 0.040849 * math.sin(2.0 * self.dangle())
        ) * 229.18

    def hour_angle(self):
        """
        Autogenerated method
        Excel formula defined in cell H3
        Original formula: =15*(C3-12.5)+($A$11)-($A$13)*15+G3/4"""
        return 15.0 * (self.hr - 12.5) + self.long - self.tz * 15.0 + self.eqt() / 4.0

    def zenith_ang(self):
        """
        Autogenerated method
        Excel formula defined in cell I3
        Original formula: =ACOS(COS(F3/(180/3.14159))*COS($A$9/(180/3.14159))*COS(H3/(180/3.14159))+SIN(F3/(180/3.14159))*SIN($A$9/(180/3.14159)))*(180/3.14159)"""
        return math.acos(
            math.cos(self.dec() / (180.0 / 3.14159))
            * math.cos(self.lat / (180.0 / 3.14159))
            * math.cos(self.hour_angle() / (180.0 / 3.14159))
            + math.sin(self.dec() / (180.0 / 3.14159))
            * math.sin(self.lat / (180.0 / 3.14159))
        ) * (180.0 / 3.14159)

    def air_mass(self):
        """
        Autogenerated method
        Excel formula defined in cell J3
        Original formula: =IF(I3<89,1/(COS(I3/(180/3.14159))+0.15/(93.885-I3)^1.25),0)"""
        if self.zenith_ang() < 89.0:
            return 1.0 / (
                math.cos(self.zenith_ang() / (180.0 / 3.14159))
                + 0.15 / (93.885 - self.zenith_ang()) ** 1.25
            )
        else:
            return 0.0

    def t_rayliegh(self):
        """
        Autogenerated method
        Excel formula defined in cell K3
        Original formula: =IF(J3>0,EXP(-0.0903*($A$15*J3/1013)^0.84*(1+$A$15*J3/1013-($A$15*J3/1013)^1.01)),0)"""
        if self.air_mass() > 0.0:
            return math.exp(
                -0.0903
                * (self.pressure_m_b * self.air_mass() / 1013.0) ** 0.84
                * (
                    1.0
                    + self.pressure_m_b * self.air_mass() / 1013.0
                    - (self.pressure_m_b * self.air_mass() / 1013.0) ** 1.01
                )
            )
        else:
            return 0.0

    def tozone(self):
        """
        Autogenerated method
        Excel formula defined in cell L3
        Original formula: =IF(J3>0,1-0.1611*($A$17*J3)*(1+139.48*($A$17*J3))^-0.3034-0.002715*($A$17*J3)/(1+0.044*($A$17*J3)+0.0003*($A$17*J3)^2),0)"""
        if self.air_mass() > 0.0:
            return (
                1.0
                - 0.1611
                * (self.ozone_cm * self.air_mass())
                * (1.0 + 139.48 * (self.ozone_cm * self.air_mass())) ** (-0.3034)
                - 0.002715
                * (self.ozone_cm * self.air_mass())
                / (
                    1.0
                    + 0.044 * (self.ozone_cm * self.air_mass())
                    + 0.0003 * (self.ozone_cm * self.air_mass()) ** 2.0
                )
            )
        else:
            return 0.0

    def t_gases(self):
        """
        Autogenerated method
        Excel formula defined in cell M3
        Original formula: =IF(J3>0,EXP(-0.0127*(J3*$A$15/1013)^0.26),0)"""
        if self.air_mass() > 0.0:
            return math.exp(
                -0.0127 * (self.air_mass() * self.pressure_m_b / 1013.0) ** 0.26
            )
        else:
            return 0.0

    def t_water(self):
        """
        Autogenerated method
        Excel formula defined in cell N3
        Original formula: =IF(J3>0,1-2.4959*J3*$A$19/((1+79.034*$A$19*J3)^0.6828+6.385*$A$19*J3),0)"""
        if self.air_mass() > 0.0:
            return 1.0 - 2.4959 * self.air_mass() * self.h2_o_cm / (
                (1.0 + 79.034 * self.h2_o_cm * self.air_mass()) ** 0.6828
                + 6.385 * self.h2_o_cm * self.air_mass()
            )
        else:
            return 0.0

    def t_aerosol(self):
        """
        Autogenerated method
        Excel formula defined in cell O3
        Original formula: =IF(J3>0,EXP(-($A$25^0.873)*(1+$A$25-$A$25^0.7088)*J3^0.9108),0)"""
        if self.air_mass() > 0.0:
            return math.exp(
                -self.taua() ** 0.873
                * (1.0 + self.taua() - self.taua() ** 0.7088)
                * self.air_mass() ** 0.9108
            )
        else:
            return 0.0

    def taa(self):
        """
        Autogenerated method
        Excel formula defined in cell P3
        Original formula: =IF(J3>0,1-0.1*(1-J3+J3^1.06)*(1-O3),0)"""
        if self.air_mass() > 0.0:
            return 1.0 - 0.1 * (1.0 - self.air_mass() + self.air_mass() ** 1.06) * (
                1.0 - self.t_aerosol()
            )
        else:
            return 0.0

    def rs(self):
        """
        Autogenerated method
        Excel formula defined in cell Q3
        Original formula: =IF(J3>0,0.0685+(1-$A$27)*(1-O3/P3),0)"""
        if self.air_mass() > 0.0:
            return 0.0685 + (1.0 - self.ba) * (1.0 - self.t_aerosol() / self.taa())
        else:
            return 0.0

    def id(self):
        """
        Autogenerated method
        Excel formula defined in cell R3
        Original formula: =IF(J3>0,0.9662*D3*O3*N3*M3*L3*K3,0)"""
        if self.air_mass() > 0.0:
            return (
                0.9662
                * self.etr()
                * self.t_aerosol()
                * self.t_water()
                * self.t_gases()
                * self.tozone()
                * self.t_rayliegh()
            )
        else:
            return 0.0

    def idn_h(self):
        """
        Autogenerated method
        Excel formula defined in cell S3
        Original formula: =IF(I3<90,R3*COS(I3/(180/3.14159)),0)"""
        if self.zenith_ang() < 90.0:
            return self.id() * math.cos(self.zenith_ang() / (180.0 / 3.14159))
        else:
            return 0.0

    def ias(self):
        """
        Autogenerated method
        Excel formula defined in cell T3
        Original formula: =IF(J3>0,D3*COS(I3/(180/3.14159))*0.79*L3*M3*N3*P3*(0.5*(1-K3)+$A$27*(1-(O3/P3)))/(1-J3+(J3)^1.02),0)"""
        if self.air_mass() > 0.0:
            return (
                self.etr()
                * math.cos(self.zenith_ang() / (180.0 / 3.14159))
                * 0.79
                * self.tozone()
                * self.t_gases()
                * self.t_water()
                * self.taa()
                * (
                    0.5 * (1.0 - self.t_rayliegh())
                    + self.ba * (1.0 - self.t_aerosol() / self.taa())
                )
                / (1.0 - self.air_mass() + self.air_mass() ** 1.02)
            )
        else:
            return 0.0

    def gh(self):
        """
        Autogenerated method
        Excel formula defined in cell U3
        Original formula: =IF(J3>0,(S3+T3)/(1-$A$29*Q3),0)"""
        if self.air_mass() > 0.0:
            return (self.idn_h() + self.ias()) / (1.0 - self.albedo * self.rs())
        else:
            return 0.0

    def time(self):
        """
        Autogenerated method
        Excel formula defined in cell V3
        Original formula: =B3+(C3-0.5)/24"""
        return self.doy + (self.hr - 0.5) / 24.0

    def direct_beam(self):
        """
        Autogenerated method
        Excel formula defined in cell W3
        Original formula: =R3"""
        return self.id()

    def direct_hz(self):
        """
        Autogenerated method
        Excel formula defined in cell X3
        Original formula: =S3"""
        return self.idn_h()

    def global_hz(self):
        """
        Autogenerated method
        Excel formula defined in cell Y3
        Original formula: =U3"""
        return self.gh()

    def dif_hz(self):
        """
        Autogenerated method
        Excel formula defined in cell Z3
        Original formula: =Y3-X3"""
        return self.global_hz() - self.direct_hz()
